#logging:
#  pattern:
#    # 日志在控制台输出格式
#    console: "%d - %msg%n"
#  file:
#    #设置日志文件保存地址和文件名
#    name: E:\env\log\sell.log
#  level:
#    #设置日志级别  要以<key value>形式
#    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1:3306/object?serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null


  mvc:
    static-path-pattern: /**
  redis:
    host: localhost
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wxa765302b7924279e
  mpAppSecret: 18ea55b358597865f5accdcb493bc928
  openAppId: wxa765302b7924279e
  openAppSecret: 18ea55b358597865f5accdcb493bc928
  mchId: 1409146202
  mchKey: 18ea55b358597865f5accdcb493bc928
  keyPath: static/api/seller.json
  notifyUrl: http://li.666600000.xyz/sell/pay/notify
  TemplateId:
    orderStatus: ChE9-_oRz1oB68fphOs5t3xgJ84eoiUz171SgRtdzFs

projecturl:
  wechatMpAuthorize: http://li.666600000.xyz/
  wechatOpenAuthorize: http://li.666600000.xyz/
  sell: http://li.666600000.xyz/





