#logging:
#  pattern:
#    # 日志在控制台输出格式
#    console: "%d - %msg%n"
#  file:
#    #设置日志文件保存地址和文件名
#    name: E:\env\log\sell.log
#  level:
#    #设置日志级别  要以<key value>形式
#    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/object?serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell


